// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/github": {
            "get": {
                "description": "Redireciona para o GitHub OAuth",
                "tags": [
                    "auth"
                ],
                "summary": "Iniciar login com GitHub",
                "responses": {
                    "302": {
                        "description": "Redireciona para GitHub"
                    }
                }
            }
        },
        "/auth/github/callback": {
            "get": {
                "description": "GitHub chama este endpoint após autorização",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Callback do GitHub OAuth",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código do GitHub",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "State anti-CSRF",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token JWT",
                        "schema": {
                            "$ref": "#/definitions/http.tokenResponse"
                        }
                    },
                    "400": {
                        "description": "invalid or expired state parameter",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidState"
                        }
                    },
                    "409": {
                        "description": "email already registered with password login",
                        "schema": {
                            "$ref": "#/definitions/http.ErrEmailConflictOAuth"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInternal"
                        }
                    },
                    "502": {
                        "description": "failed to authenticate with GitHub",
                        "schema": {
                            "$ref": "#/definitions/http.ErrGitHubAuth"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login com email e senha",
                "parameters": [
                    {
                        "description": "Credenciais",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token JWT",
                        "schema": {
                            "$ref": "#/definitions/http.tokenResponse"
                        }
                    },
                    "401": {
                        "description": "invalid email or password",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidCredentials"
                        }
                    },
                    "422": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidBody"
                        }
                    }
                }
            }
        },
        "/config": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna todas as configurações globais do sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Listar configurações",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Config"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidCredentials"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza o valor de uma chave de configuração (somente admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Atualizar configuração",
                "parameters": [
                    {
                        "description": "Chave e valor",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.updateConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Config"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidCredentials"
                        }
                    },
                    "403": {
                        "description": "admin role required",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    }
                }
            }
        },
        "/rotation": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna a fila circular de pagadores com a posição atual",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rotation"
                ],
                "summary": "Listar rodízio atual",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecase.RotationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidCredentials"
                        }
                    }
                }
            }
        },
        "/rotation/order": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Substitui a fila de pagadores (somente admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rotation"
                ],
                "summary": "Atualizar ordem do rodízio",
                "parameters": [
                    {
                        "description": "Array completo de user_ids na nova ordem",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.updateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidCredentials"
                        }
                    },
                    "403": {
                        "description": "admin role required",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    }
                }
            }
        },
        "/rotation/skip": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Avança a posição atual da fila para o próximo usuário (somente admin)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rotation"
                ],
                "summary": "Pular vez no rodízio",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidCredentials"
                        }
                    },
                    "403": {
                        "description": "admin role required",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    },
                    "409": {
                        "description": "rotation not initialized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    }
                }
            }
        },
        "/rounds": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna histórico paginado de rodadas",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rounds"
                ],
                "summary": "Listar rodadas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Página (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Itens por página (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecase.PaginatedRoundsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidCredentials"
                        }
                    }
                }
            }
        },
        "/rounds/today": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna a rodada do dia atual com campo is_payer para o usuário autenticado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rounds"
                ],
                "summary": "Rodada de hoje",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecase.TodayRoundResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidCredentials"
                        }
                    }
                }
            }
        },
        "/rounds/{id}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Pagador cancela a rodada; próximo da fila é notificado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rounds"
                ],
                "summary": "Cancelar pagamento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Round ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidCredentials"
                        }
                    },
                    "403": {
                        "description": "payer only",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    },
                    "409": {
                        "description": "round not in pending status",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    }
                }
            }
        },
        "/rounds/{id}/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Pagador confirma a rodada, abrindo para participações",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rounds"
                ],
                "summary": "Confirmar pagamento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Round ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInvalidCredentials"
                        }
                    },
                    "403": {
                        "description": "payer only",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    },
                    "409": {
                        "description": "round not in pending status",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Cria um novo usuário com email e senha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Cadastrar usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.User"
                        }
                    },
                    "409": {
                        "description": "email already registered",
                        "schema": {
                            "$ref": "#/definitions/http.ErrEmailConflict"
                        }
                    },
                    "422": {
                        "description": "name, email and password are required",
                        "schema": {
                            "$ref": "#/definitions/http.ErrValidation"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrInternal"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Config": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "domain.RotationMember": {
            "type": "object",
            "properties": {
                "position": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.Round": {
            "type": "object",
            "properties": {
                "closes_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "description": "\"YYYY-MM-DD\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "notify_at": {
                    "type": "string"
                },
                "payer_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.RoundStatus"
                }
            }
        },
        "domain.RoundStatus": {
            "type": "string",
            "enum": [
                "pending",
                "open",
                "closed",
                "cancelled"
            ],
            "x-enum-varnames": [
                "RoundStatusPending",
                "RoundStatusOpen",
                "RoundStatusClosed",
                "RoundStatusCancelled"
            ]
        },
        "domain.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "http.ErrEmailConflict": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "email already registered"
                }
            }
        },
        "http.ErrEmailConflictOAuth": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "email already registered with password login"
                }
            }
        },
        "http.ErrGitHubAuth": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "failed to authenticate with GitHub"
                }
            }
        },
        "http.ErrInternal": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal server error"
                }
            }
        },
        "http.ErrInvalidBody": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        },
        "http.ErrInvalidCredentials": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid email or password"
                }
            }
        },
        "http.ErrInvalidState": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid or expired state parameter"
                }
            }
        },
        "http.ErrValidation": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "name, email and password are required"
                }
            }
        },
        "http.loginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao@empresa.com"
                },
                "password": {
                    "type": "string",
                    "example": "s3nh4segura"
                }
            }
        },
        "http.registerRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "http.tokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "http.updateConfigRequest": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "http.updateOrderRequest": {
            "type": "object",
            "properties": {
                "user_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "usecase.PaginatedRoundsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Round"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "usecase.RotationResponse": {
            "type": "object",
            "properties": {
                "current_payer_id": {
                    "type": "string"
                },
                "current_pos": {
                    "type": "integer"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.RotationMember"
                    }
                }
            }
        },
        "usecase.TodayRoundResponse": {
            "type": "object",
            "properties": {
                "closes_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "description": "\"YYYY-MM-DD\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_payer": {
                    "type": "boolean"
                },
                "notify_at": {
                    "type": "string"
                },
                "payer_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.RoundStatus"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "API Pão de Queijo",
	Description:      "API interna para o time de desenvolvimento.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
